### ISSUE TITLE
"and" should be omitted

### ISSUE THREAD

**Issue by davedash** [divan/num2words#1]
First of all, this library is great.  Thank you.  I was writing a program to teach my kid to read numbers and this made that a breeze.

I think, however, you're supposed to omit the word "and" from written numbers.

See [this](http://dwb.unl.edu/teacher/nsf/c10/c10links/math.about.com/library/mathfiles/bl044-01a.htm).

**Comment by divan** [comment]
Thanks, Dave. Yes, you're absolutely right. I'm not a native speaker, so didn't realize the 'and' was unnecessary. Fixed in https://github.com/divan/num2words/commit/c342fa97901369bdc545123062ea7aef26568ea7.

**Comment by davedash** [comment]
Awesome thanks.
