### ISSUE TITLE
Removed unnecessary 'and'

### ISSUE THREAD

**Issue by plod** [divan/num2words#2]
I'd quite like the "and" to be an optional feature, at the moment I am vendoring to put it back in. If you'd like I could work on it and put a pull request in.

**Comment by divan** [comment]
@plod wow, I totally missed this issue :/

This just has been done via `ConvertAnd` function and available in master: https://github.com/divan/num2words/commit/59ec89ae3816cda9f1c0766ba3b4717f2cd2b46c
